### ISSUE TITLE
Lets move this to elixir-ecto/encoding repo

### ISSUE THREAD

**Issue by mjaric** [elixir-ecto/excoding#23]
Could we move this to https://github.com/elixir-ecto org?

@moogle19 , @josevalim

**Comment by mjaric** [comment]
@moogle19 , @josevalim, is this ok? We can make PRs there. It will be easier to manage contributors

**Comment by josevalim** [comment]
Fine by me. Does it work for you @moogle19?

**Comment by moogle19** [comment]
Yes, no problem. I'll transfer it right away.

**Comment by moogle19** [comment]
Hmm, it seems I can't. Can you request a transfer from you side @josevalim ?

**Comment by josevalim** [comment]
Can you add me as admin? Then I think I can.

**Comment by josevalim** [comment]
Got an invite, can you make me an owner/admin? I will transfer it next. :)

**Comment by moogle19** [comment]
Couldn't find a way to make you admin to a private repo. I just requested to transfer it to your account.

**Comment by josevalim** [comment]
Done!
